config/routes.rb
Rails.application.routes.draw do
  root "backlogs#index"
  resources :backlogs
  devise_for :users,
    controllers: {
      confirmations: "users/confirmations",
      passwords: "users/passwords",
      registrations: "users/registrations",
      sessions: "users/sessions",
      unlocks: "users/unlocks",
      invitations: "users/invitations",
    }
  resources :users, :only => [:index, :show, :update, :edit, :destroy]

  #match '/api/v1/private/backlog/get.json', controller: :"private_api/backlogs", action: :get, format: false, via: [:get]
  #match '/api/v1/private/backlog/upsert.json', controller: :"private_api/backlogs", action: :upsert, format: false, via: [:post]

  # backlog
  match "/api/v1/private/backlogs/:id/columns_and_items_get.json", controller: :"private_api/backlogs", action: :get_columns_and_items, format: false, via: [:get]
  match "/api/v1/private/backlogs/:id/item_location_update.json", controller: :"private_api/backlogs", action: :update_item_location, format: false, via: [:put]
  match "/api/v1/private/backlogs/:id/column_location_update.json", controller: :"private_api/backlogs", action: :update_column_location, format: false, via: [:put]
  # backlog column
  match "/api/v1/private/backlogs/:id/backlog_columns/create.json", controller: :"private_api/backlog_columns", action: :create, format: false, via: [:post]
  match "/api/v1/private/backlogs/:id/backlog_columns/update.json", controller: :"private_api/backlog_columns", action: :update, format: false, via: [:put]
  match "/api/v1/private/backlogs/:id/backlog_columns/destroy.json", controller: :"private_api/backlog_columns", action: :destroy, format: false, via: [:delete]
  # backlog item
  match "/api/v1/private/backlogs/:id/backlog_items/create.json", controller: :"private_api/backlog_items", action: :create, format: false, via: [:post]
  match "/api/v1/private/backlogs/:id/backlog_items/update.json", controller: :"private_api/backlog_items", action: :update, format: false, via: [:put]
  match "/api/v1/private/backlogs/:id/backlog_items/destroy.json", controller: :"private_api/backlog_items", action: :destroy, format: false, via: [:delete]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # backlog tag
  match "/api/v1/private/backlogs/:id/backlog_tags/create.json", controller: :"private_api/backlog_tags", action: :create, format: false, via: [:post]
end

app/views/layouts/application.html.slim
doctype html
html
  head
    meta content=("text/html; charset=UTF-8") http-equiv="Content-Type" /
    title Scuria
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  body
    - if user_signed_in?
      nav.navbar.navbar-expand-sm.navbar-dark.bg-dark
        = link_to("#{current_team.name}", root_path, class: "navbar-brand")
        .dropdown
          button#dropdownMenuButton.btn.btn-secondary.dropdown-toggle aria-expanded="false" aria-haspopup="true" data-toggle="dropdown" type="button"
            = current_backlog_name
          - if display_header_backlogs.length > 0
            .dropdown-menu aria-labelledby="dropdownMenuButton" style="z-index:9999"
              - display_header_backlogs.each do |backlog|
                = link_to(backlog.name, backlog_path(backlog.id), class: "dropdown-item", "data-turbolinks": false)
        #navbarNavAltMarkup.collapse.navbar-collapse.justify-content-end
          ul.navbar-nav
            li.nav-item.dropdown
              - if current_user.super
                a#navbarDropdownMenuLink.nav-link.dropdown-toggle aria-expanded="false" aria-haspopup="true" data-toggle="dropdown" href="#" role="button"
                  | 管理者メニュー
                .dropdown-menu.dropdown-menu-right aria-labelledby="navbarDropdownMenuLink"
                  = link_to("ユーザー一覧", users_path, class: "dropdown-item")
            li.nav-item.dropdown
              a#navbarDropdownMenuLink.nav-link.dropdown-toggle aria-expanded="false" aria-haspopup="true" data-toggle="dropdown" href="#" role="button"
                |チームメニュー
              .dropdown-menu.dropdown-menu-right aria-labelledby="navbarDropdownMenuLink"
                = link_to("バックログ一覧", backlogs_path, class: "dropdown-item")
            li.nav-item.dropdown
              a#navbarDropdownMenuLink.nav-link.dropdown-toggle aria-expanded="false" aria-haspopup="true" data-toggle="dropdown" href="#" role="button"
                | ユーザー設定
              .dropdown-menu.dropdown-menu-right aria-labelledby="navbarDropdownMenuLink"
                = link_to("設定編集", edit_user_registration_path, class: "dropdown-item")
                = link_to("ログアウト", destroy_user_session_path, method: :delete, data: {confirm: "ログアウトしますか？"}, class: "dropdown-item")
    = yield